//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Printing
    {
        public int PrintID { get; set; }
        public Nullable<int> BookID { get; set; }
        public Nullable<System.DateTime> PDate { get; set; }
        public Nullable<int> Number_of_Pages { get; set; }
    
        public virtual Book Book { get; set; }
    }
}
