//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Publisher
    {
        public int PubID { get; set; }
        public Nullable<int> BookID { get; set; }
        public Nullable<int> AuthorID { get; set; }
        public string BeginningChapters { get; set; }
        public string LastChapters { get; set; }
    
        public virtual Author Author { get; set; }
        public virtual Book Book { get; set; }
        public virtual Book Book1 { get; set; }
    }
}
