//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Royalty
    {
        public int RID { get; set; }
        public Nullable<int> BookID { get; set; }
        public Nullable<System.DateTime> R_Date { get; set; }
        public string Pointer { get; set; }
        public string Coefficient { get; set; }
        public string Addition { get; set; }
        public string TextType { get; set; }
    
        public virtual Book Book { get; set; }
    }
}
