//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Stock
    {
        public int SID { get; set; }
        public Nullable<int> BookID { get; set; }
        public Nullable<System.DateTime> EntranceDate { get; set; }
        public Nullable<System.DateTime> ExitDate { get; set; }
        public Nullable<int> Unit { get; set; }
        public string Explanation { get; set; }
    
        public virtual Book Book { get; set; }
    }
}
